export enum NotificationType {
  // Attendance related
  ATTENDANCE_REMINDER = 'ATTENDANCE_REMINDER',
  ATTENDANCE_LATE_WARNING = 'ATTENDANCE_LATE_WARNING',
  ATTENDANCE_ABSENCE_WARNING = 'ATTENDANCE_ABSENCE_WARNING',
  ATTENDANCE_REPORT = 'ATTENDANCE_REPORT',

  // Leave related
  LEAVE_REQUEST_SUBMITTED = 'LEAVE_REQUEST_SUBMITTED',
  LEAVE_REQUEST_APPROVED = 'LEAVE_REQUEST_APPROVED',
  LEAVE_REQUEST_REJECTED = 'LEAVE_REQUEST_REJECTED',
  LEAVE_REQUEST_UPDATED = 'LEAVE_REQUEST_UPDATED',
  LEAVE_BALANCE_LOW = 'LEAVE_BALANCE_LOW',

  // Face recognition
  FACE_VERIFICATION_REQUEST = 'FACE_VERIFICATION_REQUEST',
  FACE_VERIFICATION_SUCCESS = 'FACE_VERIFICATION_SUCCESS',
  FACE_VERIFICATION_FAILED = 'FACE_VERIFICATION_FAILED',

  // System
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
  SYSTEM_MAINTENANCE = 'SYSTEM_MAINTENANCE',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',

  // Employee
  EMPLOYEE_BIRTHDAY = 'EMPLOYEE_BIRTHDAY',
  EMPLOYEE_ANNIVERSARY = 'EMPLOYEE_ANNIVERSARY',
  PAYROLL_AVAILABLE = 'PAYROLL_AVAILABLE',
}
