// Tokens for dependency injection
export const TIMESHEET_ENTRY_REPOSITORY = Symbol('TIMESHEET_ENTRY_REPOSITORY');
export const MONTHLY_SUMMARY_REPOSITORY = Symbol('MONTHLY_SUMMARY_REPOSITORY');
export const REPORT_TEMPLATE_REPOSITORY = Symbol('REPORT_TEMPLATE_REPOSITORY');
export const EXPORT_BATCH_REPOSITORY = Symbol('EXPORT_BATCH_REPOSITORY');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
