apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: microservices-platform
build:
  artifacts:
    - image: auth-service
      context: services/auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NODE_ENV: "production"
      sync:
        manual:
          - src: "src/**/*.js"
            dest: /app/src
          - src: "src/**/*.ts"
            dest: /app/src
          - src: "package.json"
            dest: /app

    - image: zentry.api
      context: services/face-recognition
      docker:
        dockerfile: src/Zentry.API/Dockerfile
        buildArgs:
          ASPNETCORE_ENVIRONMENT: "Production"
      sync:
        manual:
          - src: "src/**/*.cs"
            dest: /app
          - src: "src/**/*.csproj"
            dest: /app

# Deploy chính được tách thành 2 giai đoạn
deploy:
  kubectl:
    manifests:
      # Giai đoạn 1: Tạo namespace và resource quotas trước
      - infra/k8s/platform/namespace.yaml
      - infra/k8s/platform/resource-quotas.yaml
      - infra/k8s/platform/network-policies.yaml

portForward:
  - resourceType: service
    resourceName: auth-srv
    namespace: default
    port: 3001
    localPort: 3001
  - resourceType: service
    resourceName: face-recognition-srv
    namespace: default
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: postgres-srv
    namespace: infrastructure
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: redis-srv
    namespace: infrastructure
    port: 6379
    localPort: 6379
  - resourceType: service
    resourceName: rabbitmq-srv
    namespace: infrastructure
    port: 15672
    localPort: 15672
  - resourceType: service
    resourceName: prometheus-srv
    namespace: monitoring
    port: 9090
    localPort: 9090
  - resourceType: service
    resourceName: grafana-srv
    namespace: monitoring
    port: 3030
    localPort: 3030

profiles:
  # Profile cho development
  - name: dev
    build:
      local:
        push: false
    portForward:
      - resourceType: service
        resourceName: auth-srv
        namespace: default
        port: 3001
        localPort: 3001
      - resourceType: service
        resourceName: face-recognition-srv
        namespace: default
        port: 8080
        localPort: 8080
      - resourceType: service
        resourceName: grafana-srv
        namespace: monitoring
        port: 3030
        localPort: 3030

  # Profile cho production
  - name: prod
    build:
      cluster: {}

  # Profile 1: Chỉ tạo namespace và platform basics
  - name: step1-namespace
    build:
      artifacts: []
    deploy:
      kubectl:
        manifests:
          - infra/k8s/platform/namespace.yaml
          - infra/k8s/platform/resource-quotas.yaml
          - infra/k8s/platform/network-policies.yaml

  # Profile 2: Deploy infrastructure sau khi namespace đã có
  - name: step2-infra
    build:
      artifacts: []
    deploy:
      kubectl:
        manifests:
          # ===== SECRETS (Deploy đầu tiên) =====
          - infra/k8s/shared/databases/postgres/postgres-secret.yaml
          - infra/k8s/shared/messaging/redis/redis-secret.yaml
          - infra/k8s/shared/messaging/rabbitmq/rabbitmq-secret.yaml
          
          # ===== CONFIGMAPS =====
          # PostgreSQL configs
          - infra/k8s/shared/databases/postgres/postgres-ha-config.yaml
          # Redis configs
          - infra/k8s/shared/messaging/redis/redis-sentinel-config.yaml
          # RabbitMQ configs
          - infra/k8s/shared/messaging/rabbitmq/rabbitmq-config.yaml
          - infra/k8s/shared/messaging/rabbitmq/rabbitmq-definitions.yaml
          
          # ===== STATEFULSETS & STORAGE =====
          # PostgreSQL HA cluster
          - infra/k8s/shared/databases/postgres/postgres-ha-statefulset.yaml
          # Redis Sentinel cluster
          - infra/k8s/shared/messaging/redis/redis-sentinel-statefulset.yaml
          # RabbitMQ HA cluster
          - infra/k8s/shared/messaging/rabbitmq/rabbitmq-statefulset.yaml
          
          # ===== MONITORING =====
          # RBAC
          - infra/k8s/shared/monitoring/prometheus-rbac.yaml
          - infra/k8s/shared/monitoring/fluentd-rbac.yaml
          # ConfigMaps
          - infra/k8s/shared/monitoring/prometheus-configmap.yaml
          - infra/k8s/shared/monitoring/fluentd-configmap.yaml
          - infra/k8s/shared/monitoring/grafana/grafana-configmap.yaml
          - infra/k8s/shared/monitoring/grafana/grafana-datasources-configmap.yaml
          # Deployments
          - infra/k8s/shared/monitoring/prometheus-depl.yaml
          - infra/k8s/shared/monitoring/grafana/grafana-deployment.yaml
          - infra/k8s/shared/monitoring/fluentd-daemonset.yaml
          # Services
          - infra/k8s/shared/monitoring/grafana/grafana-service.yaml
          
          # ===== BACKUP & DR =====
          - infra/k8s/platform/backup-cronjobs.yaml
          
          # ===== NETWORK POLICIES =====
          - infra/k8s/platform/network-policies-hardened.yaml
    portForward:
      - resourceType: service
        resourceName: postgres-srv
        namespace: infrastructure
        port: 5432
        localPort: 5432
      - resourceType: service
        resourceName: redis-srv
        namespace: infrastructure
        port: 6379
        localPort: 6379
      - resourceType: service
        resourceName: rabbitmq-srv
        namespace: infrastructure
        port: 15672
        localPort: 15672
      - resourceType: service
        resourceName: grafana-srv
        namespace: monitoring
        port: 3030
        localPort: 3030
      - resourceType: service
        resourceName: prometheus-srv
        namespace: monitoring
        port: 9090
        localPort: 9090

  # Profile 3: Deploy services sau khi infra đã sẵn sàng
  - name: step3-services
    build:
      local:
        push: false
      artifacts:
      - image: auth-service
        context: services/auth
        docker:
          dockerfile: Dockerfile
      - image: zentry.api
        context: services/face-recognition
        docker:
          dockerfile: src/Zentry.API/Dockerfile
    deploy:
      kubectl:
        manifests:
          # ===== AUTH SERVICE (HA) =====
          - infra/k8s/services/auth/configmap.yaml
          - infra/k8s/services/auth/secrets.yaml
          - infra/k8s/services/auth/deployment-ha.yaml
          
          # ===== FACE RECOGNITION SERVICE (HA) =====
          - infra/k8s/services/face-recognition/serviceaccount.yaml
          - infra/k8s/services/face-recognition/configmap.yaml
          - infra/k8s/services/face-recognition/secrets.yaml
          - infra/k8s/services/face-recognition/deployment-ha.yaml
          
          # ===== ATTENDANCE SERVICE =====
          - infra/k8s/services/attendance/serviceaccount.yaml
          - infra/k8s/services/attendance/configmap.yaml
          - infra/k8s/services/attendance/secrets.yaml
          - infra/k8s/services/attendance/deployment.yaml
          - infra/k8s/services/attendance/service.yaml
          - infra/k8s/services/attendance/hpa.yaml
          
          # ===== EMPLOYEE SERVICE =====
          - infra/k8s/services/employee/serviceaccount.yaml
          - infra/k8s/services/employee/configmap.yaml
          - infra/k8s/services/employee/secrets.yaml
          - infra/k8s/services/employee/deployment.yaml
          - infra/k8s/services/employee/service.yaml
          - infra/k8s/services/employee/hpa.yaml
          
          # ===== LEAVE SERVICE =====
          - infra/k8s/services/leave/serviceaccount.yaml
          - infra/k8s/services/leave/configmap.yaml
          - infra/k8s/services/leave/secrets.yaml
          - infra/k8s/services/leave/deployment.yaml
          - infra/k8s/services/leave/service.yaml
          - infra/k8s/services/leave/hpa.yaml
          
          # ===== NOTIFICATION SERVICE =====
          - infra/k8s/services/notification/serviceaccount.yaml
          - infra/k8s/services/notification/configmap.yaml
          - infra/k8s/services/notification/secrets.yaml
          - infra/k8s/services/notification/deployment.yaml
          - infra/k8s/services/notification/service.yaml
          - infra/k8s/services/notification/hpa.yaml
          
          # ===== REPORTING SERVICE =====
          - infra/k8s/services/reporting/serviceaccount.yaml
          - infra/k8s/services/reporting/configmap.yaml
          - infra/k8s/services/reporting/secrets.yaml
          - infra/k8s/services/reporting/deployment.yaml
          - infra/k8s/services/reporting/service.yaml
          - infra/k8s/services/reporting/hpa.yaml
          
          # ===== INGRESS (Deploy cuối cùng) =====
          - infra/k8s/platform/ingress-srv.yaml
    portForward:
      - resourceType: service
        resourceName: auth-srv
        namespace: default
        port: 3001
        localPort: 3001
      - resourceType: service
        resourceName: face-recognition-srv
        namespace: default
        port: 8080
        localPort: 8080
      - resourceType: service
        resourceName: attendance-srv
        namespace: default
        port: 3002
        localPort: 3002
      - resourceType: service
        resourceName: employee-srv
        namespace: default
        port: 3003
        localPort: 3003
      - resourceType: service
        resourceName: leave-srv
        namespace: default
        port: 3004
        localPort: 3004
      - resourceType: service
        resourceName: notification-srv
        namespace: default
        port: 3005
        localPort: 3005
      - resourceType: service
        resourceName: reporting-srv
        namespace: default
        port: 3006
        localPort: 3006

