export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const HASHING_SERVICE = 'HASHING_SERVICE';
export const EVENT_PUBLISHER = 'EVENT_PUBLISHER';
export const REFRESH_TOKENS_REPOSITORY = 'REFRESH_TOKENS_REPOSITORY';
export const JWT_SERVICE = 'JWT_SERVICE';
export const AUDIT_LOGS_REPOSITORY = 'AUDIT_LOGS_REPOSITORY';
export const TEMPORARY_PASSWORDS_REPOSITORY = 'TEMPORARY_PASSWORDS_REPOSITORY';