export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const HASHING_SERVICE = 'HASHING_SERVICE';
export const EVENT_PUBLISHER = 'EVENT_PUBLISHER';
export const REFRESH_TOKENS_REPOSITORY = 'REFRESH_TOKENS_REPOSITORY';
export const JWT_SERVICE = 'JWT_SERVICE';
export const AUDIT_LOGS_REPOSITORY = 'AUDIT_LOGS_REPOSITORY';
export const TEMPORARY_PASSWORDS_REPOSITORY = 'TEMPORARY_PASSWORDS_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY';
export const API_KEY_REPOSITORY = 'API_KEY_REPOSITORY';
export const DEVICE_SESSION_REPOSITORY = 'DEVICE_SESSION_REPOSITORY';
export const DEVICE_ACTIVITY_LOG_REPOSITORY = 'DEVICE_ACTIVITY_LOG_REPOSITORY';
export const DEVICE_SECURITY_ALERT_REPOSITORY = 'DEVICE_SECURITY_ALERT_REPOSITORY';

