// Tokens for dependency injection
export const LEAVE_TYPE_REPOSITORY = Symbol('LEAVE_TYPE_REPOSITORY');
export const HOLIDAY_REPOSITORY = Symbol('HOLIDAY_REPOSITORY');
export const LEAVE_BALANCE_REPOSITORY = Symbol('LEAVE_BALANCE_REPOSITORY');
export const LEAVE_RECORD_REPOSITORY = Symbol('LEAVE_RECORD_REPOSITORY');
export const LEAVE_BALANCE_TRANSACTION_REPOSITORY = Symbol('LEAVE_BALANCE_TRANSACTION_REPOSITORY');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
