export enum ErrorCodes {
  // General errors
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Auth specific errors
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS',
  PASSWORD_TOO_WEAK = 'PASSWORD_TOO_WEAK',
  TEMPORARY_PASSWORD_MUST_CHANGE = 'TEMPORARY_PASSWORD_MUST_CHANGE',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',

  // Notification specific errors
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ALREADY_READ = 'NOTIFICATION_ALREADY_READ',
  INVALID_NOTIFICATION_TYPE = 'INVALID_NOTIFICATION_TYPE',
  INVALID_DELIVERY_CHANNEL = 'INVALID_DELIVERY_CHANNEL',
  NOTIFICATION_SEND_FAILED = 'NOTIFICATION_SEND_FAILED',
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  INVALID_TEMPLATE_VARIABLES = 'INVALID_TEMPLATE_VARIABLES',
  
  // Preference errors
  PREFERENCE_NOT_FOUND = 'PREFERENCE_NOT_FOUND',
  INVALID_PREFERENCE_SETTING = 'INVALID_PREFERENCE_SETTING',
  
  // Push token errors
  PUSH_TOKEN_NOT_FOUND = 'PUSH_TOKEN_NOT_FOUND',
  INVALID_PUSH_TOKEN = 'INVALID_PUSH_TOKEN',
  PUSH_TOKEN_REGISTRATION_FAILED = 'PUSH_TOKEN_REGISTRATION_FAILED',
  
  // External service errors
  EMAIL_SERVICE_UNAVAILABLE = 'EMAIL_SERVICE_UNAVAILABLE',
  PUSH_SERVICE_UNAVAILABLE = 'PUSH_SERVICE_UNAVAILABLE',
  SMS_SERVICE_UNAVAILABLE = 'SMS_SERVICE_UNAVAILABLE',
  
  // Rate limiting
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  
  // Do not disturb
  DO_NOT_DISTURB_ACTIVE = 'DO_NOT_DISTURB_ACTIVE',
  
  // Employee specific errors
  EMPLOYEE_ALREADY_EXISTS = 'EMPLOYEE_ALREADY_EXISTS',
  EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_CODE_ALREADY_EXISTS = 'EMPLOYEE_CODE_ALREADY_EXISTS',
  EMPLOYEE_EMAIL_ALREADY_EXISTS = 'EMPLOYEE_EMAIL_ALREADY_EXISTS',
  DEPARTMENT_NOT_FOUND = 'DEPARTMENT_NOT_FOUND',
  POSITION_NOT_FOUND = 'POSITION_NOT_FOUND',
  POSITION_CODE_ALREADY_EXISTS = 'POSITION_CODE_ALREADY_EXISTS',
  MANAGER_NOT_FOUND = 'MANAGER_NOT_FOUND',
}
