export const EMPLOYEE_REPOSITORY = 'EMPLOYEE_REPOSITORY';
export const DEPARTMENT_REPOSITORY = 'DEPARTMENT_REPOSITORY';
export const ONBOARDING_STEP_REPOSITORY = 'ONBOARDING_STEP_REPOSITORY';
export const POSITION_REPOSITORY = 'POSITION_REPOSITORY';
export const EVENT_PUBLISHER = 'EVENT_PUBLISHER';